### ISSUE TITLE
[Sound Request] Sound of Silence

### ISSUE THREAD

**Issue by Bdthomson** [got-em/got-em#65]
https://www.youtube.com/watch?v=4zLfCnGVeL4

can you add the beginning of this
“Hello darkness my old friend"

**Comment by Bdthomson** [comment]
This is time critical @davidmenendez

**Comment by davidmenendez** [comment]
Actually can you open a PR for this? i don't know what tool i can use to crop this and grab the audio. Chris might know.

**Comment by Bdthomson** [comment]
https://github.com/got-em/got-em/pull/67
